name: Build and Publish Docker

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@master
      env:
        BUILD_DATE: $(date -u +"%Y-%m-%dT%H:%M:%SZ")
        VCS_URL: $(git config --get remote.origin.url)
        VCS_REF: $(git rev-parse --short HEAD)
      with:
        name: leavesask/gmpich
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        buildargs: BUILD_DATE,VCS_URL,VCS_REF
        buildoptions: "--compress"
